[platformio]
default_envs = lolin32

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.3
build_flags =
    -D AIRTOOLS_FIRMWARE_VERSION=0x000100
    -D AIRTOOLS_MAX_NETWORKS=64
    -D AIRTOOLS_MAX_CLIENTS=96
    -D AIRTOOLS_BLE_MTU=247

[env:lolin32]
board = lolin32
build_flags =
    ${env.build_flags}
    -D AIRTOOLS_BOARD_ID=1
    -D AIRTOOLS_HAS_DISPLAY=0
    -D AIRTOOLS_HAS_SD=0
    -D AIRTOOLS_HAS_BATTERY_ADC=1
    -D AIRTOOLS_BATTERY_ADC_PIN=35

[env:esp32dev]
board = esp32dev
build_flags =
    ${env.build_flags}
    -D AIRTOOLS_BOARD_ID=2
    -D AIRTOOLS_HAS_DISPLAY=0
    -D AIRTOOLS_HAS_SD=0
    -D AIRTOOLS_HAS_BATTERY_ADC=0

[env:nodemcu-32s]
board = nodemcu-32s
build_flags =
    ${env.build_flags}
    -D AIRTOOLS_BOARD_ID=3
    -D AIRTOOLS_HAS_DISPLAY=0
    -D AIRTOOLS_HAS_SD=0
    -D AIRTOOLS_HAS_BATTERY_ADC=0

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
build_flags =
    ${env.build_flags}
    -D AIRTOOLS_BOARD_ID=4
    -D AIRTOOLS_HAS_DISPLAY=0
    -D AIRTOOLS_HAS_SD=0
    -D AIRTOOLS_HAS_BATTERY_ADC=0

[env:esp32-s3-generic-lcd147]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
    ${env.build_flags}
    -D AIRTOOLS_BOARD_ID=5
    -D AIRTOOLS_HAS_DISPLAY=1
    -D AIRTOOLS_HAS_ST7789=1
    -D AIRTOOLS_HAS_SD=1
    -D AIRTOOLS_HAS_BATTERY_ADC=1
    -D AIRTOOLS_BATTERY_ADC_PIN=4
