#pragma once

#ifndef AIRTOOLS_FIRMWARE_VERSION
#define AIRTOOLS_FIRMWARE_VERSION 0x000100
#endif

#define AIRTOOLS_FIRMWARE_VERSION_TEXT "0.1.0"

#ifndef AIRTOOLS_BOARD_ID
#define AIRTOOLS_BOARD_ID 0
#endif

#ifndef AIRTOOLS_MAX_NETWORKS
#define AIRTOOLS_MAX_NETWORKS 64
#endif

#ifndef AIRTOOLS_MAX_CLIENTS
#define AIRTOOLS_MAX_CLIENTS 96
#endif

#ifndef AIRTOOLS_BLE_MTU
#define AIRTOOLS_BLE_MTU 247
#endif

#ifndef AIRTOOLS_MAX_HANDSHAKES
#define AIRTOOLS_MAX_HANDSHAKES 16
#endif

#ifndef AIRTOOLS_MAX_HEX_DOWNLOAD_BYTES
#define AIRTOOLS_MAX_HEX_DOWNLOAD_BYTES 8192
#endif

#ifndef AIRTOOLS_MAX_CAPTURE_FRAME_BYTES
#define AIRTOOLS_MAX_CAPTURE_FRAME_BYTES 2048
#endif

#ifndef AIRTOOLS_HANDSHAKE_MAX_FRAMES
#define AIRTOOLS_HANDSHAKE_MAX_FRAMES 6
#endif

#ifndef AIRTOOLS_HANDSHAKE_CAPTURE_BYTES
#define AIRTOOLS_HANDSHAKE_CAPTURE_BYTES 256
#endif

#ifndef AIRTOOLS_HAS_DISPLAY
#define AIRTOOLS_HAS_DISPLAY 0
#endif

#ifndef AIRTOOLS_HAS_SD
#define AIRTOOLS_HAS_SD 0
#endif

#ifndef AIRTOOLS_HAS_BATTERY_ADC
#define AIRTOOLS_HAS_BATTERY_ADC 0
#endif

#ifndef AIRTOOLS_BATTERY_ADC_PIN
#define AIRTOOLS_BATTERY_ADC_PIN -1
#endif

#define AIRTOOLS_BLE_DEVICE_NAME "AIRTOOLS-ESP32"
#define AIRTOOLS_SERVICE_UUID "7b459c40-6a5a-4e4c-9ec7-a17001500001"
#define AIRTOOLS_RX_UUID "7b459c41-6a5a-4e4c-9ec7-a17001500001"
#define AIRTOOLS_TX_UUID "7b459c42-6a5a-4e4c-9ec7-a17001500001"
